# Generated by Django 5.2.4 on 2025-07-05 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SwasthCare_seller", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_product_id",
                    models.CharField(
                        help_text="ObjectId of the food product from MongoDB",
                        max_length=255,
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True,
                        help_text="Search query used to find the product",
                        max_length=255,
                    ),
                ),
                ("search_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Cached product name for quick reference",
                        max_length=255,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="Product barcode if available",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search Histories",
                "ordering": ["-search_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-search_timestamp"],
                        name="SwasthCare__user_id_84a828_idx",
                    ),
                    models.Index(
                        fields=["food_product_id"],
                        name="SwasthCare__food_pr_24f2dd_idx",
                    ),
                ],
            },
        ),
    ]
