# Generated by Django 5.2.3 on 2025-07-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SwasthCare_seller", "0002_searchhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchHistory",
        ),
    ]
